// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HomeController from "./home_controller"
application.register("home", HomeController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ToastifyController from "./toastify_controller"
application.register("toastify", ToastifyController)
